version: latest
services:
  database:
    build:
      context: ./database
      dockerfile: database/Dockerfile
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=12345
    ports:
      - "9000:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
