version: '3'
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./sql_script.sql:/docker-entrypoint-initdb.d/database/volume
    ports:
      - "9000:9000"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database